%< code-highlight version-2.0 snow-bud >%
enclose-hig:
    '"' - '"'   -> #CE9178
    "'" - "'"   -> #CE9178
    '`' - '`'   -> #CE9178
    '/*' - '*/'    -> #D4D4D4

enclose-doc:
    '/**' - '*/'   -> #D4D4D4
    '//' - '\n'    -> #D4D4D4

enclose-low:
    '@' - ' '   -> #9CDCFE

pre-token:
    ':'     -> #CE9178

doc-token:
    '@author'       -> #4EC9B0
    '@deprecated'   -> #4EC9B0
    '@exception'    -> #4EC9B0
    '@param'        -> #4EC9B0
    '@return'       -> #4EC9B0
    '@see'          -> #4EC9B0
    '@since'        -> #4EC9B0
    '@throws'       -> #4EC9B0
    '@version'      -> #4EC9B0
    '@override'     -> #4EC9B0
    '@SuppressWarnings' -> #4EC9B0

keyword:
    'abstract'      -> #569CD6
    'assert'        -> #569CD6
    'boolean'       -> #569CD6
    'break'         -> #569CD6
    'byte'          -> #569CD6
    'case'          -> #569CD6
    'catch'         -> #569CD6
    'char'          -> #569CD6
    'class'         -> #569CD6
    'const'         -> #569CD6
    'continue'      -> #569CD6
    'default'       -> #569CD6
    'do'            -> #569CD6
    'double'        -> #569CD6
    'else'          -> #569CD6
    'enum'          -> #569CD6
    'extends'       -> #569CD6
    'final'         -> #569CD6
    'finally'       -> #569CD6
    'float'         -> #569CD6
    'for'           -> #569CD6
    'goto'          -> #569CD6
    'if'            -> #569CD6
    'implements'    -> #569CD6
    'import'        -> #569CD6
    'instanceof'    -> #569CD6
    'int'           -> #569CD6
    'interface'     -> #569CD6
    'long'          -> #569CD6
    'native'        -> #569CD6
    'new'           -> #569CD6
    'package'       -> #569CD6
    'private'       -> #569CD6
    'protected'     -> #569CD6
    'public'        -> #569CD6
    'return'        -> #569CD6
    'short'         -> #569CD6
    'static'        -> #569CD6
    'strictfp'      -> #569CD6
    'super'         -> #569CD6
    'switch'        -> #569CD6
    'synchronized'  -> #569CD6
    'this'          -> #569CD6
    'throw'         -> #569CD6
    'throws'        -> #569CD6
    'transient'     -> #569CD6
    'try'           -> #569CD6
    'void'          -> #569CD6
    'volatile'      -> #569CD6
    'while'         -> #569CD6
    'true'          -> #569CD6
    'false'         -> #569CD6
    'null'          -> #569CD6
    'var'           -> #569CD6
    'record'        -> #569CD6
    'sealed'        -> #569CD6
    'permits'       -> #569CD6
    'System'        -> #4EC9B0
    'String'        -> #4EC9B0
    'Integer'       -> #4EC9B0
    'Boolean'       -> #4EC9B0
    'Object'        -> #4EC9B0
    'Exception'     -> #4EC9B0
    'RuntimeException' -> #4EC9B0
