%< code-highlight version-2.0 snow-bud >%
enclose-hig:
    '//' - '\n'     -> #cccccc
    '/*' - '*/'     -> #ccc
    '"' - '"'       -> #7d7
    "'" - "'"       -> #5a5

enclose-doc:
    '/**' - '*/'    -> #ccc // 文档类型

enclose-low:
    // 注解类型
    '@' - ' '   -> rgb(200, 100, 100)

pre-token:
    ':'     -> rgba(119, 153, 119, 1)

doc-token:
    '@return'   -> red

keyword:
    'class'     -> orange
    'int'       -> #a55
